name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Update Docker to latest CE version 
      run: ./update_docker

    - name: Setup Plugin
      run: ./setup_plugin
    
    - name: Test Plugin 
      run: |
        docker help
        docker changelog 
