name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Query Metadata Service
      run: curl -s -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2019-02-01" | jq -r '.'
      
    - name: Install GOSS
      run: curl -fsSL https://goss.rocks/install | GOSS_VER=v0.3.6 GOSS_DST=~ sh
      
    - name: Install apt-rdepends
      run: sudo apt install apt-rdepends -y
      
    #- name: Generate OS Test Report
    # run: cd ~ && for package in $(dpkg --get-selections|sort | awk '{print $1}'); do ./goss autoadd package ${package}; done
      
    - name: Update Docker to latest CE version 
      run: ./update_docker
      
    - name: Run rdepends with GOSS
      run: cd ~ && ./goss command "apt-rdepends docker"

    - name: Setup Plugin
      run: ./setup_plugin
    
    - name: Test Plugin 
      run: |
        docker help
        docker changelog |tee -a changelog.log 

    - uses: actions/upload-artifact@master
      with:
        name: "Docker Engine Changelog"
        path:  ./changelog.log 
        
    - name: GOSS Validate
      run: cd ~ && ./goss validate --format nagios
