name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    
    - uses: tomwillfixit/goss@master
      with:
        goss_command:  goss add command "ls"
    
    # Setup
    - uses: actions/checkout@v1
    
    - name: Query Metadata Service
      run: curl -s -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2019-02-01" | jq -r '.' |tee -a /tmp/metadata.log
      
    - name: Install GOSS
      run: curl -fsSL https://goss.rocks/install | GOSS_VER=v0.3.6 GOSS_DST=~ sh
      
    - name: Install apt-rdepends
      run: sudo apt install apt-rdepends -y
      
    #- name: Generate OS Test Report
    # run: cd ~ && for package in $(dpkg --get-selections|sort | awk '{print $1}'); do ./goss autoadd package ${package}; done
      
    - name: Update Docker to latest CE version 
      run: ./update_docker
      
    - name: Run rdepends with GOSS
      run: cd ~ && ./goss add command "apt-rdepends docker" |tee -a /tmp/docker.deps

    - name: Setup Plugin
      run: ./setup_plugin

    # Test

    - name: Test Plugin 
      run: |
        docker help
        docker changelog |tee -a /tmp/changelog.log 

    - name: GOSS Validate
      run: cd ~ && ./goss validate --format documentation |tee -a /tmp/goss.log

    # Save Artifacts
    
    - uses: actions/upload-artifact@master
      with:
        name: "Metadata Log"
        path:  /tmp/metadata.log
        
    - uses: actions/upload-artifact@master
      with:
        name: "Docker Engine Changelog"
        path:  /tmp/changelog.log 
        
    - uses: actions/upload-artifact@master
      with:
        name: "Docker Dependencies"
        path:  /tmp/docker.deps
        
    - uses: actions/upload-artifact@master
      with:
        name: "GOSS log"
        path:  /tmp/goss.log    
